# 로컬 개발 환경 설정
server:
  port: 8080

spring:
  datasource:
    # H2 인메모리 DB 설정
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  api:
    key: local-test-key-12345
    url: http://localhost:8081/api
